package config

import _ "embed"

// SchemaYAML is the canonical flattened YAML field-path schema for Config,
// generated by cmd/config-schema. Embed makes it available at runtime for
// schema printing and validation tooling without requiring a filesystem path.
//
// Regenerate: scripts/release/gen-schema.sh
//
//go:embed schema.yaml
var SchemaYAML []byte
