// cmd/config-schema/main.go
// Emits a JSON Schema (draft-07, expressed in YAML) for config.Config.
//
// Modes:
//   - No args: emit JSON Schema YAML to stdout.
//   - --fields: read JSON Schema YAML from stdin, print sorted dotted leaf paths.
//
// Generated output is committed as pkg/config/schema.yaml.
// Regenerate: scripts/release/gen-schema.sh
package main

import (
	"fmt"
	"io"
	"os"
	"reflect"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/keelcore/keel/pkg/config"
)

var yamlUnmarshalerType = reflect.TypeOf((*yaml.Unmarshaler)(nil)).Elem()

// fieldConstraints holds additional JSON Schema keywords to merge into specific
// field schemas, keyed by dotted yaml-tag path.
var fieldConstraints = map[string]map[string]interface{}{
	// All listener ports
	"listeners.http.port":    {"minimum": 1, "maximum": 65535},
	"listeners.https.port":   {"minimum": 1, "maximum": 65535},
	"listeners.h3.port":      {"minimum": 1, "maximum": 65535},
	"listeners.health.port":  {"minimum": 1, "maximum": 65535},
	"listeners.ready.port":   {"minimum": 1, "maximum": 65535},
	"listeners.startup.port": {"minimum": 1, "maximum": 65535},
	"listeners.admin.port":   {"minimum": 1, "maximum": 65535},
	// Backpressure
	"backpressure.high_watermark": {"minimum": 0.0, "maximum": 1.0},
	"backpressure.low_watermark":  {"minimum": 0.0, "maximum": 1.0},
	"backpressure.heap_max_bytes": {"minimum": 0},
	// Security
	"security.max_header_bytes":        {"minimum": 1},
	"security.max_request_body_bytes":  {"minimum": 0},
	"security.max_response_body_bytes": {"minimum": 0},
	"security.hsts_max_age":            {"minimum": 0},
	// Limits
	"limits.max_concurrent": {"minimum": 0},
	"limits.queue_depth":    {"minimum": 0},
	// Sidecar
	"sidecar.xff_mode":                          {"enum": []string{"append", "replace", "strip"}},
	"sidecar.xff_trusted_hops":                  {"minimum": 0},
	"sidecar.circuit_breaker.failure_threshold": {"minimum": 1},
	"sidecar.upstream_url":                      {"format": "uri"},
	// ExtAuthz
	"ext_authz.transport": {"enum": []string{"http", "opa"}},
	// Logging
	"logging.level":                {"enum": []string{"debug", "info", "warn", "error"}},
	"logging.remote_sink.protocol": {"enum": []string{"http", "syslog"}},
	// TLS/ACME
	"tls.acme.email":  {"format": "email"},
	"tls.acme.ca_url": {"format": "uri"},
	// Tracing
	"tracing.otlp.endpoint": {"format": "uri"},
}

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--fields" {
		extractAndPrintFields(os.Stdin)
		return
	}

	root := buildObjectSchema(reflect.TypeOf(config.Config{}), "")
	schema := map[string]interface{}{
		"$schema":              "https://json-schema.org/draft/2019-09/schema",
		"title":                "Keel Configuration",
		"description":          "Generated by cmd/config-schema/main.go \u2014 do not edit manually. Regenerate: scripts/release/gen-schema.sh",
		"type":                 "object",
		"additionalProperties": false,
		"properties":           root["properties"],
	}

	out, err := yaml.Marshal(schema)
	if err != nil {
		fmt.Fprintf(os.Stderr, "yaml.Marshal: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("# Generated by cmd/config-schema/main.go \u2014 do not edit manually.")
	fmt.Println("# Regenerate: scripts/release/gen-schema.sh")
	fmt.Print(string(out))
}

// buildSchema dispatches on the kind of t and returns the JSON Schema map for
// that type. path is the dotted field path used to look up fieldConstraints.
func buildSchema(t reflect.Type, path string) map[string]interface{} {
	// Dereference pointer types.
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	var schema map[string]interface{}

	switch t.Kind() {
	case reflect.Struct:
		if isLeafStruct(t) {
			schema = map[string]interface{}{
				"type":        "string",
				"description": `Go duration string (e.g. "5s", "1m30s", "500ms")`,
			}
		} else {
			schema = buildObjectSchema(t, path)
		}
	case reflect.Bool:
		schema = map[string]interface{}{"type": "boolean"}
	case reflect.String:
		schema = map[string]interface{}{"type": "string"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		schema = map[string]interface{}{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		schema = map[string]interface{}{"type": "number"}
	case reflect.Slice:
		elem := t.Elem()
		for elem.Kind() == reflect.Ptr {
			elem = elem.Elem()
		}
		if elem.Kind() == reflect.String {
			schema = map[string]interface{}{
				"type":  "array",
				"items": map[string]interface{}{"type": "string"},
			}
		} else {
			schema = map[string]interface{}{"type": "array"}
		}
	default:
		schema = map[string]interface{}{}
	}

	// Merge any field-specific constraints.
	if constraints, ok := fieldConstraints[path]; ok {
		for k, v := range constraints {
			schema[k] = v
		}
	}

	return schema
}

// buildObjectSchema returns a JSON Schema object node for the struct type t.
func buildObjectSchema(t reflect.Type, path string) map[string]interface{} {
	// Dereference pointer types.
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	props := map[string]interface{}{}
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag := f.Tag.Get("yaml")
		if tag == "" || tag == "-" {
			continue
		}
		name := strings.SplitN(tag, ",", 2)[0]
		if name == "" || name == "-" {
			continue
		}

		var fieldPath string
		if path == "" {
			fieldPath = name
		} else {
			fieldPath = path + "." + name
		}

		props[name] = buildSchema(f.Type, fieldPath)
	}

	return map[string]interface{}{
		"type":                 "object",
		"additionalProperties": false,
		"properties":           props,
	}
}

// isLeafStruct reports whether t should be treated as a scalar leaf (e.g.
// config.Duration) rather than recursed into as an object.
func isLeafStruct(t reflect.Type) bool {
	if t.Implements(yamlUnmarshalerType) {
		return true
	}
	if reflect.PointerTo(t).Implements(yamlUnmarshalerType) {
		return true
	}
	return false
}

// extractAndPrintFields reads a JSON Schema YAML from r, walks all leaf
// property paths, and prints them sorted one per line.
func extractAndPrintFields(r io.Reader) {
	var raw map[string]interface{}
	dec := yaml.NewDecoder(r)
	if err := dec.Decode(&raw); err != nil {
		fmt.Fprintf(os.Stderr, "decode: %v\n", err)
		os.Exit(1)
	}

	fields := walkProperties(raw, "")
	sort.Strings(fields)
	for _, f := range fields {
		fmt.Println(f)
	}
}

// walkProperties recursively collects dotted leaf paths from a JSON Schema map.
func walkProperties(schema map[string]interface{}, prefix string) []string {
	raw, ok := schema["properties"]
	if !ok {
		return nil
	}
	props, ok := raw.(map[string]interface{})
	if !ok {
		return nil
	}

	var result []string
	for name, val := range props {
		var dotted string
		if prefix == "" {
			dotted = name
		} else {
			dotted = prefix + "." + name
		}

		child, ok := val.(map[string]interface{})
		if !ok {
			result = append(result, dotted)
			continue
		}

		// If the child has its own "properties", it is a nested object — recurse.
		if _, hasProps := child["properties"]; hasProps {
			result = append(result, walkProperties(child, dotted)...)
		} else {
			result = append(result, dotted)
		}
	}
	return result
}
